platform :ios, '9.0'

target 'Honeybee' do

use_frameworks!

pod 'SnapKit', '~> 3.0.2'


  # Pods for Honeybee

  target 'HoneybeeTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'HoneybeeUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
