language: objective-c
#osx_image: xcode8.3
branches:
 only:
 - master
xcode_workspace: Honeybee.xcworkspace
xcode_scheme: Honeybee
xcode_sdk: iphonesimulator9.3
script:
 - xcodebuild -scheme Honeybee -workspace Honeybee.xcworkspace -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 6S,OS=9.1' build test
after_success:
 - bash <(curl -s https://codecov.io/bash)
